# Generated by Django 5.1.3 on 2024-11-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_client_age_client_points_client_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Asset66.png', null=True, upload_to='images/'),
        ),
    ]
