# Generated by Django 5.1.3 on 2024-11-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_client_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/Asset66.png', null=True, upload_to='images/'),
        ),
    ]
