# Generated by Django 5.1.3 on 2024-11-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_client_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInquiry',
            fields=[
                ('pkadmin_inquiry', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_inquiry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('pkid', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_from', models.BigIntegerField(blank=True, null=True)),
                ('user_to', models.BigIntegerField(blank=True, null=True)),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'block_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardCategory',
            fields=[
                ('pkcategory', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'board_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardPosts',
            fields=[
                ('pkboardpost', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('pkboard', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'boards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('pkconfiguration', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(max_length=126)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inquiries',
            fields=[
                ('pkinquiry', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('subject', models.CharField(blank=True, max_length=128, null=True)),
                ('message', models.TextField()),
                ('is_read', models.IntegerField()),
                ('parent_pkinquiry', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'inquiries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('pkmatch', models.BigAutoField(primary_key=True, serialize=False)),
                ('matched', models.IntegerField(blank=True, null=True)),
                ('date_time', models.CharField(blank=True, max_length=50, null=True)),
                ('accepted', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('seen', models.IntegerField(blank=True, null=True)),
                ('new', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessageTemplates',
            fields=[
                ('pkmessage_template', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'message_templates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('pkphoto', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField(blank=True, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('pkpoint', models.BigAutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('datetime', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PointsBundle',
            fields=[
                ('pkpoint_bundle', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promo_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.TextField(blank=True, db_collation='utf16_unicode_ci', null=True)),
                ('description', models.TextField(blank=True, db_collation='utf16_unicode_ci', null=True)),
                ('sku', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=100, null=True)),
                ('call_minutes', models.IntegerField(blank=True, null=True)),
                ('mail_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'points_bundle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('pkpost_comment', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, db_collation='utf8mb4_unicode_520_ci', null=True)),
                ('fkpost', models.BigIntegerField(blank=True, null=True)),
                ('datetime', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=50, null=True)),
            ],
            options={
                'db_table': 'post_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('pkpost_like', models.BigAutoField(primary_key=True, serialize=False)),
                ('fkpost', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('pkpost', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, db_collation='utf16_unicode_ci', null=True)),
                ('datetime', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=20, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostUnlikes',
            fields=[
                ('pkpost_unlike', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'post_unlikes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('pkpurchase', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('pkuser', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=100, null=True)),
                ('password', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=100, null=True)),
                ('middlename', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, db_collation='utf16_unicode_ci', null=True)),
                ('job_title', models.TextField(blank=True, db_collation='utf16_unicode_ci', null=True)),
                ('company', models.TextField(blank=True, db_collation='utf16_unicode_ci', null=True)),
                ('school', models.TextField(blank=True, db_collation='utf16_unicode_ci', null=True)),
                ('location', models.TextField(blank=True, db_collation='utf16_unicode_ci', null=True)),
                ('remember_token', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=128, null=True)),
                ('email', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=128, null=True)),
                ('region', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=128, null=True)),
                ('fb_linked', models.IntegerField(blank=True, null=True)),
                ('ig_linked', models.IntegerField(blank=True, null=True)),
                ('fb_account_id', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=50, null=True)),
                ('socket_id', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=50, null=True)),
                ('salt', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=255, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('gender_preference', models.IntegerField(blank=True, null=True)),
                ('distancethreshold', models.CharField(blank=True, db_collation='utf16_unicode_ci', db_column='distanceThreshold', max_length=255, null=True)),
                ('role_id', models.IntegerField()),
                ('age_verified', models.IntegerField(blank=True, null=True)),
                ('dummy_account', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.IntegerField(blank=True, null=True)),
                ('presence_of_children', models.IntegerField(blank=True, null=True)),
                ('marriage_desire', models.IntegerField(blank=True, null=True)),
                ('like_children_or_not', models.IntegerField(blank=True, null=True)),
                ('presence_of_pet', models.IntegerField(blank=True, null=True)),
                ('smoker', models.IntegerField(blank=True, null=True)),
                ('drink', models.IntegerField(blank=True, null=True)),
                ('holiday', models.IntegerField(blank=True, null=True)),
                ('hobbie', models.TextField(blank=True, db_collation='utf16_unicode_ci', null=True)),
                ('bloodtype', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=20, null=True)),
                ('flip_count', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=255, null=True)),
                ('notify_updates', models.IntegerField(blank=True, null=True)),
                ('character', models.TextField(blank=True, db_collation='utf16_unicode_ci', null=True)),
                ('introduction', models.TextField(blank=True, db_collation='utf16_unicode_ci', null=True)),
                ('registration_datetime', models.CharField(blank=True, max_length=120, null=True)),
                ('drop_calls', models.IntegerField(blank=True, null=True)),
                ('notify_likes', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(blank=True, null=True)),
                ('token', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=255, null=True)),
                ('mail_count', models.IntegerField(blank=True, null=True)),
                ('call_minutes', models.FloatField(blank=True, null=True)),
                ('udid', models.CharField(db_collation='utf16_unicode_ci', max_length=128)),
                ('push_token', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=255, null=True)),
                ('resetpasswordcode', models.CharField(blank=True, db_collation='utf16_unicode_ci', max_length=45, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserUnlikes',
            fields=[
                ('pkuser_unlike', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user_unlikes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewedProfile',
            fields=[
                ('pkprofile_view', models.BigAutoField(primary_key=True, serialize=False)),
                ('fkviewer', models.BigIntegerField(blank=True, null=True)),
                ('fkviewed_profile', models.BigIntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('liked', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'viewed_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewPurchases',
            fields=[
                ('bundle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateField(blank=True, max_length=50, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('pkpurchase', models.AutoField(primary_key=True, serialize=False)),
                ('fkuser', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_purchases',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
