# Generated by Django 5.1.3 on 2024-12-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_admininquiry_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelTable(
            name='messages',
            table='messages',
        ),
    ]
